debug = false

logLevel = "ERROR"
defaultEntryPoints = ["http"]

# Generate Hash: https://www.askapache.com/online-tools/htpasswd-generator/
[web]
address = ":40030"
[web.auth.basic]
users = ["admin:$apr1$3ybtl8zp$GXOO2GpgRJAU5MRTQGQQ.1"]

[entryPoints]
    [entryPoints.http]
    address = ":80"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "needpc.fr"
watch = true
exposedbydefault = false
swarmmode = true

[consul]
endpoint = "consul:8500"
watch = true
prefix = "traefik"